# Generated by Django 2.1.3 on 2018-11-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0002_movie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user',
            new_name='created_by',
        ),
    ]
